### PR TITLE
Do not use outdated http://rm-rf.ca/tito url

### PR DESCRIPTION
**Pull request by glensc**
Did not know what other url to use, so used github url

### CODE REVIEW

**Comment by glensc** [comment]
Some other URLs that have no replacement:

```
[~/relup/tito/tito(ERR) (url)] ➔ g grep rm-rf.ca
doc/index.md:* [Tito release announcements](http://rm-rf.ca/blogs/dgoodwin)
setup.py:    author_email='dgoodwin@rm-rf.ca',
```

**Comment by FrostyX** [comment]
Thank you for the PR @glensc!

> doc/index.md:* [Tito release announcements](http://rm-rf.ca/blogs/dgoodwin)

Can you please put https://github.com/dgoodwin/tito/releases there?

> setup.py:    author_email='dgoodwin@rm-rf.ca',

Yep, I don't know about this one. I would definitely put this link into a comment somewhere https://github.com/dgoodwin/tito/graphs/contributors but what about the email ... People seem to put multiple emails there https://stackoverflow.com/a/10005265/3285282 so you can maybe put mine, yours if you want and whoever wants will add himself. It's not optimal but I am just not going to create a mailing list for Tito :D.

Or we can abuse e.g. `devel@lists.fedoraproject.org` a little.

Or we can maybe remove the `author_email` entirely since we don't provide a PyPI package.

**Comment by FrostyX** [comment]
Btw don't mind the Travis failure, it is a known issue and it is already fixed in another PR.

**Comment by FrostyX** [comment]
Meanwhile, I've submitted #362.

**Pull request closed without merging**
