### PR TITLE
Use --no-rebuild-srpm for scratch builds in KojiReleaser

### LINKED ISSUE #382: Can KojiReleaser with builder.test=1 use Koji's new (1.21) --no-rebuild-srpm option?
Koji-1.21 now [allows skipping SRPM rebuild for scratch builds](https://pagure.io/koji/pull-request/2083).  This seems perfect to me for doing quicker test builds.  I'm not sure if there would be any downsides.

### PR DESCRIPTION
**Pull request by FrostyX**
Fix #382

### CODE REVIEW

**Comment by FrostyX** [comment]
Thank you for the review @jflorian,
I updated the condition to accommodate also the `builder.test = 1` setting from the `releasers.conf` config file.

PTAL

**Comment by FrostyX** [comment]
By the way, please nevermind the failing Travis CI, it is not related to this change. I tried to resubmit a build from `master` that previously succeeded and it fails now, ... I will fix it in a separate PR.

**Comment by jflorian** [comment]
@FrostyX that now works, but I discovered that Koji fails if passed `--no-rebuild-srpm` without also being passed `--scratch`.  That doesn't seem correct to me and I'm wondering if you concur and that I should raise this issue with the  Koji project.   It seems like an unnecessary limitation but in reviewing the PR [Add rebuild_srpm option of BuildTask](https://pagure.io/koji/issue/1719), I'm inclined to think it will go nowhere.

I can appreciate their reasoning.  If I'm not mistaken, the concept of a "test" build is entirely with tito and while similar to Koji's scratch option, brings something different.  I've also just learned I can set a tag "extra" option `rebuild_srpm=False` and maybe that's a better approach for me, though it would mean about twice as much tag maintenance for each distro rel branch.

**Comment by FrostyX** [comment]
> If I'm not mistaken, the concept of a "test" build is entirely with tito and while similar to Koji's scratch option

Yep, "test" in Tito terms means building from the latest commit instead of the latest tag. Scratch builds are koji term for builds that won't end up in a release.

> but I discovered that Koji fails if passed --no-rebuild-srpm without also being passed --scratch. That doesn't seem correct to me and I'm wondering if you concur and that I should raise this issue with the Koji project. 

In the #382 you linked https://pagure.io/koji/pull-request/2083 that explicitly mentions skipping the SRPM rebuild for scratch builds so it feels like the koji `--no-rebuild-srpm` should be used only if `--scratch` was passed to Tito. I am gonna check with Koji guys and write here some summary.

**Comment by tkopecek** [comment]
As @FrostyX write - Yes, it is allowed only for scratch builds. For production ones user can't force this option.

**Comment by FrostyX** [comment]
Thank you @tkopecek, so I've updated the patch to only use the `--no-rebuild-srpm` koji parameter only when both `--scratch` and `--test` (or their config options) are used for Tito.

**Comment by FrostyX** [comment]
@jflorian what do you think about the PR in this state?

**Comment by jflorian** [comment]
@FrostyX that looks fine.  It doesn't help my use case, but perhaps my practices should change.  I've done almost all of my test builds without `--scratch` because I want those test builds to land in a dist repo for consumption by test clients.  If I use `--scratch` then those clients must install rpms using Koji URLs which can be a pain.  I understand that if the Koji project wants to retain this hard line, then there's nothing tito can do about it.  However, for what most users would want and expect, what you have now looks correct.

**Comment by tkopecek** [comment]
Btw, isn't fedora infra using somwhere scratch repos /every scratch build trigger a simple repository with that build/?

**Comment by FrostyX** [comment]
@jflorian, Okay, thank you for the review. I am merging.

**Pull request merged**
