### PR TITLE
<gitroot>/tito wrapper

### PR DESCRIPTION
**Pull request by praiskup**
This makes executing of Tito-from-Git a bit more convenient.

### CODE REVIEW

**Comment by FrostyX** [comment]
I've always been running Tito from git using e.g.

```bash
PYTHONPATH=/home/jkadlcik/git/tito/src/ python3 /home/jkadlcik/git/tito/src/tito/cli.py build --rpm
```

so personally, I don't have a need for the wrapper. If you find it useful, we can merge though. But in that case, please add some docstring at the top of the script discouraging people from using it unless they are working on Tito code.

**Comment by FrostyX** [comment]
> There already is an ugly stderr output, do you prefer doc, the ugly output, or both? (I prefer just one of them)

I don't have a strong preference, it can be either stderr output, docstring, or both. The problem I have with the stderr as it is right now is that the message is cryptic and it doesn't provide any explanation. I would prefer something like

```
Warning: Running Tito from a git repository is not supported. 
If you are not a developer working on Tito code, please install it properly 
https://github.com/rpm-software-management/tito/blob/master/doc/index.md#install
```

**Comment by praiskup** [comment]
> the message is cryptic and it doesn't provide any explanation

Good point, PTAL

**Review by FrostyX — APPROVED** [review]

**Comment by FrostyX** [comment]
Thank you for the changes.

**Pull request merged**
