### PR TITLE
Drop unused urllib.request import

### PR DESCRIPTION
**Pull request by FrostyX**
Fix RHBZ 1982135

### CODE REVIEW

**Comment by FrostyX** [comment]
The import probably a leftover from the first implementation that didn't use the `%_disable_source_fetch` macro, right @schlupov ?

**Comment by praiskup** [comment]
+1

**Comment by schlupov** [comment]
yes, +1

**Comment by ifireice** [comment]
Hi,

Could you please release a new version with this fix?

**Comment by FrostyX** [comment]
Hello @ifireice,
sure. I just created https://github.com/rpm-software-management/tito/releases/tag/tito-0.6.19-1
and submitted the updates to Fedora.

**Comment by ifireice** [comment]
Thanks very much =)

**Pull request merged**
