### PR TITLE
Bump the ENVRA built directly from git master branch

### PR DESCRIPTION
**Pull request by praiskup**
Fixes: #480

### CODE REVIEW

**Comment by praiskup** [comment]
This would allow us to consume packit-built packages in `sudo dnf copr enable @rpm-software-management/tito`.

**Comment by FrostyX** [comment]
Thank you for the PR @praiskup,
can we simply do `tito tag` for tagging new versions or do we have to `tito tag --use-version=...` to get rid of the suffix?

**Comment by praiskup** [comment]
Yes, you have to do `tito tag --use-version`, otherwise:
```
-Version: 0.6.24.post1
+Version: 0.6.25.post1
```

**Comment by praiskup** [comment]
Good point, updated.

**Comment by FrostyX** [comment]
> Good point, updated.

That's exactly what I meant. Thank you :-)

**Comment by praiskup** [comment]
Uh oh? :-)

```
$ sudo dnf -y copr enable @rpm-software-management/tito
$ sudo dnf update tito
Updating and loading repositories:
 Copr repo for tito owned by @rpm-software-management                                                                                                                                               100% |   8.6 KiB/s |   4.0 KiB |  00m00s
Repositories loaded.
Nothing to do.
$ rpm -q tito
tito-0.6.24-2.fc39.noarch
```

**Comment by praiskup** [comment]
Hm we produce package named `tito-tito` :D seems like tito versioning is not used at all. Lemme submit another patch then.

**Pull request merged**
