### PR TITLE
Will now copy both source files and patch files declared in the spec

### LINKED ISSUE #463: Tito fails to copy patches from the spec during srpm build causing a failure
Observe the following output regarding `smartmontools-5.38-defaultconf.patch` - it is copied into the tar but not into the directory. This is a bug, `rpmbuild` fails.

```
Copying git source to: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb
Command: cd /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/ && tar xzf smartmontools-next-git-182.802bcdb.tar.gz
Status code: 0
Command output: 

Show contents of the directory structure we just extracted:
['tests', 'smartmontools.sysconf', 'smartmontools.spec', 'smartmontools-5.38-defaultconf.patch', 'smartmontools', 'smartmon.te.f33', 'smartmon.te', 'smartmon.if', 'smartmon.fc', 'smartdnotify', 'drivedb.h', '.tito', '.gitmodules', '.gitignore']
Looking for .spec in /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb
Using file: smartmontools.spec
Command: cp /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb.tar.gz /tmp/tito/
Status code: 0
Command output: 

Wrote: /tmp/tito/smartmontools-next-git-182.802bcdb.tar.gz
Copying /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools.sysconf -> /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartdnotify -> /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.te -> /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.if -> /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.fc -> /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.te.f33 -> /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES
Creating srpm from spec file: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools.spec
*NOT* using dist at all
Command: rpm --eval '%scl'
Status code: 0
Command output: %scl


D: created directory(s) /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/BUILDROOT mode 0755
setting SOURCE_DATE_EPOCH=1680652800
error: Bad file: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-5.38-defaultconf.patch: No such file or directory

RPM build errors:
    Bad file: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-5.38-defaultconf.patch: No such file or directory


ERROR: Error running command: rpmbuild -vvv --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-smartmontools-next3w3pecfg" --define "_sourcedir /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES" --define "_builddir /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito"   --nodeps -bs /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools.spec

Status code: 1

Command output: ['', 'D: created directory(s) /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/BUILDROOT mode 0755', 'setting SOURCE_DATE_EPOCH=1680652800', 'error: Bad file: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-5.38-defaultconf.patch: No such file or directory', '', 'RPM build errors:', '    Bad file: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg/SOURCES/smartmontools-5.38-defaultconf.patch: No such file or directory']

WARNING: Leaving rpmbuild files in: /tmp/tito/rpmbuild-smartmontools-next3w3pecfg
```

Notice that the file specified in patch is not copied. This is because the following code does not process patch files:

https://github.com/rpm-software-management/tito/blob/39449a8cc2d5f22cea828b8032de6fc5bfcb0f43/src/tito/builder/main.py#L530-L532C33

### PR DESCRIPTION
**Pull request by arcivanov**
Also fix some spelling errors

fixes #463

### CODE REVIEW

**Comment by arcivanov** [comment]
with the above PR the srpm build succeeds as follows:

```
Copying git source to: /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb
Command: cd /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/ && tar xzf smartmontools-next-git-182.802bcdb.tar.gz
Status code: 0
Command output: 

Show contents of the directory structure we just extracted:
['tests', 'smartmontools.sysconf', 'smartmontools.spec', 'smartmontools-5.38-defaultconf.patch', 'smartmontools', 'smartmon.te.f33', 'smartmon.te', 'smartmon.if', 'smartmon.fc', 'smartdnotify', 'drivedb.h', '.tito', '.gitmodules', '.gitignore']
Looking for .spec in /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb
Using file: smartmontools.spec
Command: cp /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb.tar.gz /tmp/tito/
Status code: 0
Command output: 

Wrote: /tmp/tito/smartmontools-next-git-182.802bcdb.tar.gz
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools.sysconf -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartdnotify -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.te -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.if -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.fc -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmon.te.f33 -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Copying /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools-5.38-defaultconf.patch -> /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES
Creating srpm from spec file: /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools.spec
*NOT* using dist at all
Command: rpm --eval '%scl'
Status code: 0
Command output: %scl


D: created directory(s) /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/BUILDROOT mode 0755
setting SOURCE_DATE_EPOCH=1680652800
D: Signature: size(4404)+pad(4)
D: Signature: size(4404)+pad(4)
Wrote: /tmp/tito/smartmontools-next-7.4.138-1.git.182.802bcdb.fc38.src.rpm


Command: rpmbuild -vvv --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf" --define "_sourcedir /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES" --define "_builddir /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito"   --nodeps -bs /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/SOURCES/smartmontools-next-git-182.802bcdb/smartmontools.spec

Status code: 0

Command output: ['', 'D: created directory(s) /tmp/tito/rpmbuild-smartmontools-nexta2joqqqf/BUILDROOT mode 0755', 'setting SOURCE_DATE_EPOCH=1680652800', 'D: Signature: size(4404)+pad(4)', 'D: Signature: size(4404)+pad(4)', 'Wrote: /tmp/tito/smartmontools-next-7.4.138-1.git.182.802bcdb.fc38.src.rpm']

Found wrote line: /tmp/tito/smartmontools-next-7.4.138-1.git.182.802bcdb.fc38.src.rpm
```

**Comment by arcivanov** [comment]
@FrostyX This now blocks COPR builds so please merge ASAP if possible and release new version of tito.

https://download.copr.fedorainfracloud.org/results/karellen/smartmontools-next/srpm-builds/06132422/builder-live.log.gz

**Comment by xsuchy** [comment]
Hmm, the original purpose of Tito was to be able to have applied patches in upstream git. And with tito.distributionbuilder.DistributionBuilder tito will create these patches on the fly.
But if you really want to use it this way... then I see no harm in accepting this PR.

**Review by xsuchy — APPROVED** [review]

**Comment by arcivanov** [comment]
I'm using it with Submoduleaware Builder and patching the submodule files external to the project.

**Comment by arcivanov** [comment]
@FrostyX bump

**Comment by FrostyX** [comment]
This is a feature that multiple people recently asked about.
Thank you for implementing it.

I am merging and going to do a new release right after.

**Comment by FrostyX** [comment]
The new version is 0.6.24
https://bodhi.fedoraproject.org/updates/?packages=tito

**Pull request merged**
