### PR TITLE
Describe how to release tito

### PR DESCRIPTION
**Pull request by FrostyX**
So we can be sure that every maintainer does it the same way.

### CODE REVIEW

**Comment by FrostyX** [comment]
I used this in Copr releaser

    project_name = @rpm-software-management/tito

I suppose that if we transfer the project to the rpm-software-management namespace on GitHub, we probably can have also Copr project with this name. But let's wait with merging until its done.

**Comment by ernestask** [comment]
Or, if dogfooding tito, with the same GitHub Actions (I’ll get to writing up a proposal eventually). Otherwise, I don’t see anything to complain about.

**Comment by FrostyX** [comment]
> Or, if dogfooding tito, with the same GitHub Actions (I’ll get to writing up a proposal eventually).

I would prefer that. I think that when implementing these RFEs
https://github.com/dgoodwin/tito/milestone/2
the release process will be also quite simplified

**Comment by FrostyX** [comment]
We already got the Copr project, so this is not blocked anymore
https://copr.fedorainfracloud.org/coprs/g/rpm-software-management/tito/

**Pull request merged**
