### PR TITLE
test packit

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
I reported this issue https://github.com/packit/packit-service/issues/920 because it doesn't seem insecure to just trigger the build.

**Comment by praiskup** [comment]
@FrostyX  PTAL.  This commit should be just enough.

**Comment by FrostyX** [comment]
Thank you for the PR @praiskup,
I fixed the Travis CI in PR#396, can you please rebase?

Also, I am a bit confused about how can I see the results of packit builds, since the details button points to the documentation instead. I would like to debug them before we merge.

**Comment by praiskup** [comment]
> I am a bit confused about how can I see the results of packit builds

I am not able to run the builds as I have no write permissions on this repo.  You have to run /packit build again.

**Comment by FrostyX** [comment]
Awesome, all checks have passed. Thank you very much.
Hopefully, https://github.com/packit/packit-service/issues/920 gets resolved, so running checks is fully automatized, but it is helpful even now.

I will definitely configure also _my_ other projects to use packit.

**Pull request merged**
