### PR TITLE
chore: add new issues into the CPT's Kanban

### PR DESCRIPTION
**Pull request by praiskup**
This commit requires specifying the ADD_TO_PROJECT_PAT secret - already done.

### CODE REVIEW

**Comment by FrostyX** [comment]
I can merge this, no problem. But do we really want to have all Tito issues in our tracker @praiskup? There are a lot of them.

**Comment by xsuchy** [comment]
I agree with @FrostyX - we do not want to work on every issue of Tito. Just the important ones, that we can add to our Kanban manually.

**Comment by praiskup** [comment]
This only adds new issues, I think.  WRT capacity planning, I think all our issues deserve the triage. Also, it's not likely other team members are likely to reply to new issues if they are not in Kanban...  but... if this seems wrong, let's discuss it on the meeting on Monday?

BTW. I already added resalloc-related packages in `praiskup/` namespace, and added a [mock PR](https://github.com/rpm-software-management/mock/pull/1280)

**Comment by praiskup** [comment]
I'm the only one who thinks would be a profitable change, so closing.

**Pull request closed without merging**
